# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to genw22boyerate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36eb0f305af54c927fc2a2bb8e4e5fcf4d8fd2cfeca491052c3f9abd1192dfb5c8440244f6e22df0ce08cdb868851a500f77e9833a5022e0fbc307b02a9b0ef6
  twilio_account_sid: ACc13bbb979de2978d818095b76c5f5f19
  twilio_auth_token: b59a802dcfcaba1512975fb12097fd1f
  twilio_twiml_app_sid: AP4bb01b7b60b4da6aebb2d6f25960c0a4
  twilio_twiml_app_sid_queue_calling: AP71a902241983cf9142280679e9082985
  twilio_twiml_app_sid_quest_calling: AP50b88f7af512cb9256753f1cdb0ee8c2
  twilio_twiml_app_sid_basic_calling: AP2444b54c6057d77afa21a8b18e955b0b
  twilio_phone_number: +12183166108
  twilio_phone_number2: +17012034430
  stripe_publishable_key: pk_test_7CMIjTOkDl8S6fkOImYJ8Qz5
  stripe_secret_key: sk_test_FQN03AnepMDNcZaFFduIsVJS
  stripe_connect_client_id: ca_5qamk5Dt98nk4LcYpzrgDgYk6ARmn4rw

test:
  secret_key_base: 7ba5d866db45f54a13fa5a13e191ffbf80980ef3203e3ea4cd4f73a88470e2acf58e1a96619f24bff151d869fe5912c55831515b7329cf88cc92ec9e7ea89c48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 36eb0f305af54c927fc2a2bb8e4e5fcf4d8fd2cfeca491052c3f9abd1192dfb5c8440244f6e22df0ce08cdb868851a500f77e9833a5022e0fbc307b02a9b0ef6
  twilio_account_sid: ACc13bbb979de2978d818095b76c5f5f19
  twilio_auth_token: b59a802dcfcaba1512975fb12097fd1f
  twilio_twiml_app_sid: AP4bb01b7b60b4da6aebb2d6f25960c0a4
  twilio_twiml_app_sid_queue_calling: AP71a902241983cf9142280679e9082985
  twilio_twiml_app_sid_quest_calling: AP50b88f7af512cb9256753f1cdb0ee8c2
  twilio_twiml_app_sid_basic_calling: AP2444b54c6057d77afa21a8b18e955b0b
  twilio_phone_number: +12183166108
  twilio_phone_number2: +17012034430
  stripe_publishable_key: pk_test_7CMIjTOkDl8S6fkOImYJ8Qz5
  stripe_secret_key: sk_test_FQN03AnepMDNcZaFFduIsVJS
  stripe_connect_client_id: ca_5qamk5Dt98nk4LcYpzrgDgYk6ARmn4rw
